### ISSUE TITLE
[nx template]: create an component but occur an error

### ISSUE THREAD

**Issue by ChangYinShung** [fs-tw/abp.ng#31]
@fs-tw/schematics version: 1.1.0
Step 1. Create an angular app by nx 

Step 2. User `@fs-tw/schematics` to create an route name `users` , there has an error in  users.component.ts
![image](https://github.com/fs-tw/abp.ng/assets/2546026/35034f52-8a3d-4a75-b301-f298561b6998)

fix action:
path `/app/test-app/shared/tabs-service.ts` and add code  will be fix
``` javascript
@Injectable()
export class RoutesService extends AbstractNavTreeService<ABP.Route> {

}

**Comment by yinchang0626** [comment]
已知錯誤，是我的Application 範本在Shared忘了補上
已修正，下版本就會更新修補，先暫時手動補
